node('nodejs') {
    stage('build') {
        script {
            openshift.withCluster() {
                openshift.withProject() {
                    openshift.startBuild("nodejs-ex").logs("-f")
                }
            }
        }
    }

    stage('deploy') {
        script {
            openshift.withCluster() {
                openshift.withProject() {
                    def rm = openshift.selector("dc", "nodejs-ex").rollout()
                }
            }
        }
    }

}
